# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e3b566cb3c61d3d87fb470964264a16"
name = "dimitar-shop-test-app"
handle = "dimitar-shop-test-app"
application_url = "https://imported-td-deadline-aug.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dimitar-shop-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://imported-td-deadline-aug.trycloudflare.com/auth/callback",
  "https://imported-td-deadline-aug.trycloudflare.com/auth/shopify/callback",
  "https://imported-td-deadline-aug.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
