# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "069061cad618c88e1b34657bc770aa28"
name = "Content Exporter"
handle = "content-exporter"
application_url = "https://matches-providence-higher-delayed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dimitar-shop-app-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_files,read_publications,unauthenticated_read_content,write_content,write_customers,write_files,write_online_store_navigation,write_online_store_pages,write_products,write_publications"

[auth]
redirect_urls = [
  "https://matches-providence-higher-delayed.trycloudflare.com/auth/callback",
  "https://matches-providence-higher-delayed.trycloudflare.com/auth/shopify/callback",
  "https://matches-providence-higher-delayed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
